export const labels = [
  "💬 I'm Online",
  "🔥 Live Now",
  "👀 Watch Me",
  "❤️ Say Hi",
  "🎥 I'm Streaming",
  "💘 Don't Miss Me",
  "✨ I'm Glowing",
  "🎉 Let's Go",
  "👋 I'm Waiting",
  "😈 Feeling Curious?",
  "🌟 Vibes On",
  "🚀 Go Inside",
  "😍 I'm Stunning",
  "🎬 It's Showtime",
  "🥵 Too Hot to Miss",
  "📲 Tap In",
  "💎 Just You & Me",
  "⏳ Right Now Only",
  "👄 Look Who's Live",
  "🧡 All Eyes on Me",
  "📺 Must-See Moment",
  "💃 Catch the Show",
  "🔒 For You Only",
  "🎁 Surprise Inside",
  "🫦 Say Something Sweet",
  "🌶️ Hot & Live",
  "🎀 Something Special",
  "💥 Instant Spark",
  "🖤 Don't Scroll",
  "🥰 I Look Amazing"
];